import {
  AiOutlineBuild,
  AiOutlineProject,
  AiOutlineUsergroupAdd,
} from 'react-icons/ai';
import { LuLayoutDashboard } from 'react-icons/lu';
import { HiOutlineTicket, HiOutlineUsers } from 'react-icons/hi';
import Sidebar, { MenuItem } from './components/Sidebar';
import './globals.css';

export const metadata = {
  title: 'Bug Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const menuItems: MenuItem[] = [
    {
      id: 1,
      label: 'Dashboard',
      icon: <LuLayoutDashboard />,
      route: '/',
    },
    {
      id: 2,
      label: 'Projects',
      icon: <AiOutlineProject />,
      route: '/projects',
      submenus: [
        {
          id: 21,
          label: 'Company',
          icon: <AiOutlineBuild />,
          route: '/about/company',
        },
        {
          id: 22,
          label: 'Team',
          icon: <AiOutlineUsergroupAdd />,
          route: '/about/team',
        },
      ],
    },
    {
      id: 3,
      label: 'Tickets',
      icon: <HiOutlineTicket />,
      route: '/tickets',
    },
    {
      id: 4,
      label: 'Users',
      icon: <HiOutlineUsers />,
      route: '/users',
    },
  ];
  return (
    <html lang="en">
      <body className="font-semibold">
        <Sidebar menuItems={menuItems}>{children}</Sidebar>
      </body>
    </html>
  );
}
